_backend: hdf5
_class_name: GRModel
_init_arg_names:
- discrimination_prior
- discrimination_prior_scale
- dtype
- eta_scale
- full_rank
- include_independent
- item_keys
- kappa_scale
- missing_val
- num_people
- parameterization
- person_key
- positive_discriminations
- rank
- response_cardinality
- slab_df
- slab_scale
- vi_mode
- weight_exponent
dimensional_decay: 0.25
dimensions: 1
discrimination_prior: half_normal
discrimination_prior_scale: 2.0
dtype: float64
eta_scale: 0.01
full_rank: false
include_independent: false
item_keys:
- Q1
- Q2
- Q3
- Q4
- Q5
- Q6
- Q7
- Q8
- Q9
- Q10
- Q11
- Q12
- Q13
- Q14
- Q15
- Q16
- Q17
- Q18
- Q19
- Q20
- Q21
- Q22
- Q23
- Q24
- Q25
- Q26
- Q27
- Q28
- Q29
- Q30
- Q31
- Q32
- Q33
- Q34
- Q35
- Q36
- Q37
- Q38
- Q39
- Q40
kappa_scale:
- - - - 0.01
missing_val: -9999
num_items: 40
num_people: 11243
parameterization: softplus
person_key: person
positive_discriminations: true
rank: 0
response_cardinality: 2
slab_df: 4
slab_scale: 2.0
var_list:
- mu
- difficulties0
- discriminations
- abilities
vi_mode: advi
weight_exponent: 1.0
