_class_name: NeuralGRModel
decay: 0.25
dim: 1
dtype: float64
eta_scale: 0.1
full_rank: false
include_independent: false
item_keys:
- E1
- E2
- E3
- E4
- E5
- E6
- E7
- E8
- E9
- E10
- E11
- E12
- E13
- E14
- E15
- E16
- E17
- E18
- E19
- E20
- E21
- E22
- E23
- E24
- E25
- E26
- E27
- E28
- E29
- E30
- E31
- E32
- E33
- E34
- E35
- E36
- E37
- E38
- E39
- E40
- E41
- E42
- E43
- E44
- E45
- E46
- E47
- E48
- E49
- E50
- E51
- E52
- E53
- E54
- E55
- E56
- E57
- E58
- E59
- E60
- S1
- S2
- S3
- S4
- S5
- S6
- S7
- S8
- S9
- S10
- S11
- S12
- S13
- S14
- S15
- S16
- S17
- S18
- S19
- S20
- S21
- S22
- S23
- S24
- S25
- S26
- S27
- S28
- S29
- S30
- S31
- S32
- S33
- S34
- S35
- S36
- S37
- S38
- S39
- S40
- S41
- S42
- S43
- S44
- S45
- S46
- S47
- S48
- S49
- S50
- S51
- S52
- S53
- S54
- S55
- S56
- S57
- S58
- S59
- S60
kappa_scale: 0.5
missing_val: -9999
nn_hidden_sizes:
- 32
num_people: 13256
positive_discriminations: true
response_cardinality: 4
vi_mode: advi
weight_exponent: 1.0
