_class_name: NeuralGRModel
decay: 0.25
dim: 1
dtype: float64
eta_scale: 0.1
full_rank: false
include_independent: false
item_keys:
- Q1
- Q2
- Q3
- Q4
- Q5
- Q6
- Q7
- Q8
- Q9
- Q10
- Q11
- Q12
- Q13
- Q14
- Q15
- Q16
- Q17
- Q18
- Q19
- Q20
- Q21
- Q22
kappa_scale: 0.5
missing_val: -9999
nn_hidden_sizes:
- 32
num_people: 9881
positive_discriminations: true
response_cardinality: 9
vi_mode: advi
weight_exponent: 1.0
